storage:
    type: SQLITE #Availables: [MYSQL, POSTGRESQL, MARIADB and SQLITE]
    file: 'database.db' #comment this to use MYSQL, POSTGRESQL or MARIADB type.
    #database: 'test' 
    #address: 'localhost'
    #port: 3306
    #username: 'root'
    #password: ''
message:
   default-language: en_us
   message-path: 'lang/messages-<language>.yml'
